# Generated by Django 4.2.7 on 2023-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_blogentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='sign_of_publication',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='признак публикации'),
        ),
    ]
