# Generated by Django 4.2.7 on 2023-12-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_blogentry_sign_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='number_of_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество просмотров'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название версии')),
                ('number', models.FloatField(blank=True, null=True, verbose_name='Номер версии')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
