# Generated by Django 4.2.7 on 2023-12-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='статус публикации'),
        ),
    ]
