# Generated by Django 4.2.7 on 2023-12-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_publication', 'Can publish products'), ('set_category', 'Can edit product category'), ('set_description', 'Can edit product description')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
